# Generated by Django 5.2.6 on 2026-03-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='webrtc_offer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
