# Generated by Django 5.2.6 on 2026-01-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_category_id_report_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='priorite',
        ),
        migrations.AddField(
            model_name='report',
            name='lieu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
