# Generated by Django 5.2.6 on 2026-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_category_remove_report_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
