# Generated by Django 5.2.6 on 2026-01-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
