# Generated by Django 5.2.6 on 2026-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
