# Generated by Django 5.2.6 on 2026-02-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
